import type {
  AnimationConfig,
  LayerAnimationConfig,
  PresetId,
  EffectType,
} from "./types";
import { DEFAULT_LAYER_ANIM, DEFAULT_TRANSFORM, ALL_EFFECTS } from "./types";

/** Mood-based category for preset organization (user-facing) */
export type PresetCategory =
  | "calm"
  | "cinematic"
  | "dramatic"
  | "retro"
  | "cyberpunk"
  | "abstract";

export const PRESET_CATEGORIES: { id: PresetCategory; label: string; emoji: string }[] = [
  { id: "calm", label: "Calma", emoji: "🌌" },
  { id: "cinematic", label: "Cinemático", emoji: "🎬" },
  { id: "dramatic", label: "Dramático", emoji: "🔥" },
  { id: "retro", label: "Retro", emoji: "📼" },
  { id: "cyberpunk", label: "Cyberpunk", emoji: "🤖" },
  { id: "abstract", label: "Abstracto", emoji: "🔮" },
];

export interface PresetMeta {
  id: PresetId;
  name: string;
  emoji: string;
  tagline: string;
  description: string;
  /** mood-based category for filtering in the UI */
  category: PresetCategory;
  /** builds per-layer config from a base layer (depth 0..1, index) */
  buildLayer: (depth: number, index: number, total: number) => Omit<LayerAnimationConfig, "layerId">;
  base: Pick<
    AnimationConfig,
    | "intensity"
    | "speed"
    | "parallaxEnabled"
    | "liquidEnabled"
    | "particlesEnabled"
    | "shimmerEnabled"
    | "chromaticAberration"
    | "vignette"
    | "renderMode"
    | "mouseSmoothing"
  > & {
    perspective?: number;
    rotate3dStrength?: number;
  };
  effects?: Partial<Record<EffectType, boolean>>;
  /** whether this preset is "advanced" (v2) */
  v2?: boolean;
}


// helper: prime-ish phase offset per layer so animations desync
const primePhase = (i: number) => (i * 0.37) % 1;

export const PRESETS: PresetMeta[] = [
  // ============ ORIGINAL 8 ============
  {
    id: "dream",
    name: "Dream",
    emoji: "🌙",
    category: "calm",
    tagline: "Respiración sutil + líquido + parallax",
    description:
      "El efecto por defecto. La imagen respira, se balancea dulcemente y ondula como agua. Parallax suave con el mouse.",
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 8 + depth * 28,
      mouseVelocityInfluence: 0.3,
      breathing: true,
      breathingAmp: 0.6 + depth * 0.6,
      sway: true,
      swayAmp: 0.5 + depth * 0.6,
      floatY: depth > 0.6,
      floatAmp: 0.6,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1,
      speed: 1,
      parallaxEnabled: true,
      liquidEnabled: true,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 1.2,
      vignette: 0.25,
      renderMode: "css",
      mouseSmoothing: 0.06,
    },
    effects: { dust: true },
  },
  {
    id: "float",
    name: "Float",
    emoji: "🪶",
    category: "calm",
    tagline: "Capas flotando en el aire",
    description:
      "Cada capa flota y deriva suavemente como si estuviera suspendida en el aire. Sin distorsión líquida.",
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 12 + depth * 36,
      mouseVelocityInfluence: 0.5,
      inertia: 0.25,
      breathing: true,
      breathingAmp: 0.8,
      sway: depth > 0.4,
      swayAmp: 0.4,
      floatY: true,
      floatAmp: 0.5 + depth * 0.8,
      driftX: true,
      driftAmp: 0.4 + depth * 0.5,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1.1,
      speed: 0.85,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: true,
      shimmerEnabled: false,
      chromaticAberration: 0.6,
      vignette: 0.15,
      renderMode: "css",
      mouseSmoothing: 0.05,
    },
  },
  {
    id: "pulse",
    name: "Pulse",
    emoji: "💓",
    category: "dramatic",
    tagline: "Latido rítmico orgánico",
    description:
      "La imagen late como un corazón. Respiración intensa y opacidad pulsante, sin parallax.",
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: depth * 14,
      breathing: true,
      breathingAmp: 1.2 + depth * 0.6,
      glow: depth > 0.5,
      glowAmp: 0.5,
      sway: false,
      floatY: false,
      liquid: false,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1.3,
      speed: 0.7,
      parallaxEnabled: false,
      liquidEnabled: false,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 0.4,
      vignette: 0.35,
      renderMode: "css",
      mouseSmoothing: 0.06,
    },
  },
  {
    id: "liquid",
    name: "Liquid",
    emoji: "💧",
    category: "abstract",
    tagline: "Distorsión líquida LSD",
    description:
      "Máxima distorsión SVG tipo agua. La imagen se ondula como una superficie líquida.",
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 6 + depth * 16,
      breathing: true,
      breathingAmp: 0.4,
      sway: true,
      swayAmp: 0.3,
      liquid: true,
      liquidScale: 10 + depth * 8,
      wave: true,
      waveAmp: 0.6,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1,
      speed: 0.9,
      parallaxEnabled: true,
      liquidEnabled: true,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 2.4,
      vignette: 0.3,
      renderMode: "css",
      mouseSmoothing: 0.07,
    },
  },
  {
    id: "cinematic3d",
    name: "Cinematic 3D",
    emoji: "🎬",
    category: "cinematic",
    tagline: "Parallax por mapa de profundidad (WebGL)",
    description:
      "Usa el mapa de profundidad generado por IA para un parallax 3D real píxel-a-píxel.",
    buildLayer: () => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 0,
      breathing: true,
      breathingAmp: 0.4,
      sway: false,
      liquid: false,
    }),
    base: {
      intensity: 1.2,
      speed: 1,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: false,
      shimmerEnabled: false,
      chromaticAberration: 1.8,
      vignette: 0.4,
      renderMode: "css",
      mouseSmoothing: 0.05,
    },
  },
  {
    id: "shimmer",
    name: "Shimmer",
    emoji: "✨",
    category: "calm",
    tagline: "Brillo de luz barriente",
    description:
      "Un haz de luz barre la imagen lentamente. Sutil movimiento + shimmer.",
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 4 + depth * 12,
      breathing: true,
      breathingAmp: 0.3,
      sway: false,
      liquid: false,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 0.8,
      speed: 1.2,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: false,
      shimmerEnabled: true,
      chromaticAberration: 0.8,
      vignette: 0.2,
      renderMode: "css",
      mouseSmoothing: 0.06,
    },
  },
  {
    id: "boil",
    name: "Hand-drawn Boil",
    emoji: "✏️",
    category: "retro",
    tagline: "Temblor de ilustración animada",
    description:
      "El 'boiling' de la animación tradicional: temblor orgánico continuo como dibujo a mano.",
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 2 + depth * 6,
      breathing: false,
      sway: false,
      liquid: true,
      liquidScale: 4 + depth * 4,
      jitter: true,
      jitterAmp: 0.8,
      floatY: true,
      floatAmp: 0.3,
      phaseOffset: primePhase(i),
      durationMultiplier: 1.6,
    }),
    base: {
      intensity: 1.4,
      speed: 1.6,
      parallaxEnabled: true,
      liquidEnabled: true,
      particlesEnabled: false,
      shimmerEnabled: false,
      chromaticAberration: 0.3,
      vignette: 0.1,
      renderMode: "css",
      mouseSmoothing: 0.08,
    },
  },
  {
    id: "kenburns",
    name: "Ken Burns",
    emoji: "🎥",
    category: "cinematic",
    tagline: "Zoom y pan lento cinematográfico",
    description:
      "El clásico efecto Ken Burns: zoom muy lento + pan sutil. Sin parallax de mouse.",
    buildLayer: () => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 0,
      breathing: false,
      sway: false,
      floatY: false,
      liquid: false,
    }),
    base: {
      intensity: 0.7,
      speed: 0.5,
      parallaxEnabled: false,
      liquidEnabled: false,
      particlesEnabled: false,
      shimmerEnabled: false,
      chromaticAberration: 0,
      vignette: 0.2,
      renderMode: "css",
      mouseSmoothing: 0.06,
    },
  },

  // ============ NEW v2 ADVANCED PRESETS ============
  {
    id: "aurora",
    name: "Aurora",
    emoji: "🌌",
    category: "calm",
    tagline: "Deriva de color etérea",
    description:
      "Capas con hue-drift lento, glow pulsante y deriva sutil. Crea una aurora boreal de color sobre la imagen.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 6 + depth * 18,
      mouseVelocityInfluence: 0.4,
      inertia: 0.2,
      breathing: true,
      breathingAmp: 0.5 + depth * 0.4,
      sway: true,
      swayAmp: 0.4,
      driftX: true,
      driftAmp: 0.5,
      hueDrift: true,
      hueDriftAmp: 6 + depth * 6,
      glow: depth > 0.5,
      glowAmp: 0.4,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1,
      speed: 0.8,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 1.6,
      vignette: 0.3,
      renderMode: "css",
      mouseSmoothing: 0.05,
    },
    effects: { bokeh: true, dust: true },
  },
  {
    id: "underwater",
    name: "Underwater",
    emoji: "🌊",
    category: "abstract",
    tagline: "Inmersión acuosa con caustics",
    description:
      "Líquido intenso + wave + focus pull + glow. Simula estar bajo el agua con caustics de luz.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 4 + depth * 10,
      mouseVelocityInfluence: 0.6,
      inertia: 0.3,
      breathing: true,
      breathingAmp: 0.4,
      sway: true,
      swayAmp: 0.6,
      liquid: true,
      liquidScale: 14 + depth * 8,
      wave: true,
      waveAmp: 1.2,
      focusPull: depth < 0.4,
      focusAmp: 1.5,
      glow: true,
      glowAmp: 0.3,
      hueDrift: true,
      hueDriftAmp: 4,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1.2,
      speed: 0.7,
      parallaxEnabled: true,
      liquidEnabled: true,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 2.8,
      vignette: 0.45,
      renderMode: "css",
      mouseSmoothing: 0.04,
    },
    effects: { bokeh: true, lightleak: true },
  },
  {
    id: "ethereal",
    name: "Ethereal",
    emoji: "🪽",
    category: "calm",
    tagline: "Susurrante y divino",
    description:
      "Brillo suave, niebla, partículas bokeh y deriva etérea. Para retratos y escenas celestiales.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 5 + depth * 14,
      mouseVelocityInfluence: 0.3,
      inertia: 0.2,
      breathing: true,
      breathingAmp: 0.7 + depth * 0.3,
      sway: true,
      swayAmp: 0.3,
      floatY: depth > 0.3,
      floatAmp: 0.5,
      glow: true,
      glowAmp: 0.5 + depth * 0.3,
      focusPull: depth < 0.3,
      focusAmp: 1,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 0.9,
      speed: 0.75,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 0.8,
      vignette: 0.25,
      renderMode: "css",
      mouseSmoothing: 0.04,
    },
    effects: { fog: true, bokeh: true, lightleak: true },
  },
  {
    id: "noir",
    name: "Noir",
    emoji: "🕶️",
    category: "cinematic",
    tagline: "Cine negro con grano",
    description:
      "Alto contraste, grano animado, viñeta fuerte y parallax lento. Estética de cine negro.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 3 + depth * 10,
      mouseVelocityInfluence: 0.2,
      inertia: 0.15,
      breathing: true,
      breathingAmp: 0.3,
      sway: depth > 0.5,
      swayAmp: 0.2,
      jitter: depth > 0.6,
      jitterAmp: 0.4,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1,
      speed: 0.85,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: false,
      shimmerEnabled: false,
      chromaticAberration: 0,
      vignette: 0.55,
      renderMode: "css",
      mouseSmoothing: 0.05,
    },
    effects: { grain: true },
  },
  {
    id: "cosmic",
    name: "Cosmic",
    emoji: "☄️",
    category: "dramatic",
    tagline: "Cosmos con polvo estelar",
    description:
      "Glow intenso, hue drift cósmico, chromatic aberration y muchísimas partículas. Para escenas espaciales.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 8 + depth * 30,
      mouseVelocityInfluence: 0.7,
      inertia: 0.35,
      breathing: true,
      breathingAmp: 0.6 + depth * 0.6,
      sway: true,
      swayAmp: 0.5,
      driftX: true,
      driftAmp: 0.6,
      glow: true,
      glowAmp: 0.8 + depth * 0.4,
      hueDrift: true,
      hueDriftAmp: 12,
      chromatic: depth > 0.5,
      chromaticAmp: 2,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1.4,
      speed: 0.9,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 3.2,
      vignette: 0.35,
      renderMode: "css",
      mouseSmoothing: 0.04,
    },
    effects: { bokeh: true, dust: true, lightleak: true, godrays: false },
  },

  // ============ NEW v3 CREATIVE PRESETS ============
  // Each pushes a distinct aesthetic with carefully tuned amplitude + phase combos.

  {
    id: "paper",
    name: "Paper",
    emoji: "📄",
    category: "retro",
    tagline: "Papel temblante con grano",
    description:
      "Jitter sutil + breathing + grano. Simula una foto de papel viejo temblando levemente. Cálido y analógico.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 3 + depth * 8,
      mouseVelocityInfluence: 0.15,
      inertia: 0.1,
      breathing: true,
      breathingAmp: 0.3 + depth * 0.2,
      sway: depth > 0.4,
      swayAmp: 0.25,
      jitter: true,
      jitterAmp: 0.4 + depth * 0.3,
      floatY: depth > 0.6,
      floatAmp: 0.25,
      shadowDrift: depth > 0.5,
      phaseOffset: primePhase(i),
      durationMultiplier: 1.4,
    }),
    base: {
      intensity: 0.85,
      speed: 0.9,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: false,
      shimmerEnabled: false,
      chromaticAberration: 0.2,
      vignette: 0.4,
      renderMode: "css",
      mouseSmoothing: 0.07,
    },
    effects: { grain: true, lightleak: true },
  },
  {
    id: "glass",
    name: "Glass",
    emoji: "🪞",
    category: "abstract",
    tagline: "Vidrio esmerilado refractante",
    description:
      "Chromatic aberration fuerte + z-tilt + sway3d. La imagen se ve a través de un vidrio que se inclina y refracta la luz.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 6 + depth * 22,
      mouseVelocityInfluence: 0.4,
      inertia: 0.2,
      breathing: true,
      breathingAmp: 0.4,
      zTilt: true,
      zTiltAmp: 2 + depth * 2,
      sway3d: depth > 0.4,
      sway3dAmp: 3 + depth * 2,
      chromatic: true,
      chromaticAmp: 2.5,
      focusPull: depth < 0.3,
      focusAmp: 0.8,
      glow: depth > 0.6,
      glowAmp: 0.3,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1.1,
      speed: 0.95,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 3.6,
      vignette: 0.3,
      renderMode: "css",
      mouseSmoothing: 0.05,
    },
    effects: { bokeh: true, dust: true },
  },
  {
    id: "vintage",
    name: "Vintage",
    emoji: "📽️",
    category: "retro",
    tagline: "Película 8mm con gate weave",
    description:
      "Gate weave + grano + scanlines + light leak. Replica una proyección de película antigua con todos sus defectos encantadores.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 2 + depth * 6,
      mouseVelocityInfluence: 0.1,
      inertia: 0.05,
      breathing: true,
      breathingAmp: 0.25,
      sway: depth > 0.5,
      swayAmp: 0.2,
      jitter: true,
      jitterAmp: 0.5,
      scan: true,
      scanAmp: 0.4,
      hueDrift: true,
      hueDriftAmp: 3,
      shadowDrift: depth > 0.6,
      phaseOffset: primePhase(i),
      durationMultiplier: 1.2,
    }),
    base: {
      intensity: 0.95,
      speed: 0.85,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: false,
      shimmerEnabled: false,
      chromaticAberration: 1.4,
      vignette: 0.5,
      renderMode: "css",
      mouseSmoothing: 0.08,
      gateWeave: true,
    },
    effects: { grain: true, lightleak: true },
  },
  {
    id: "techno",
    name: "Techno",
    emoji: "🤖",
    category: "cyberpunk",
    tagline: "Glitch digital rítmico",
    description:
      "Pulso rítmico + scan + jitter + chromatic. Estética cyberpunk con latido techno y artefactos digitales.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 4 + depth * 14,
      mouseVelocityInfluence: 0.5,
      inertia: 0.15,
      heartbeat: true,
      heartbeatAmp: 0.8 + depth * 0.4,
      scan: true,
      scanAmp: 0.6,
      jitter: depth > 0.4,
      jitterAmp: 0.6,
      chromatic: true,
      chromaticAmp: 2 + depth * 1.5,
      glow: depth > 0.5,
      glowAmp: 0.5,
      phaseOffset: primePhase(i),
      durationMultiplier: 0.8,
    }),
    base: {
      intensity: 1.3,
      speed: 1.3,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 3.8,
      vignette: 0.35,
      renderMode: "css",
      mouseSmoothing: 0.04,
    },
    effects: { grain: true },
  },
  {
    id: "zen",
    name: "Zen",
    emoji: "🧘",
    category: "calm",
    tagline: "Meditación lenta y mínima",
    description:
      "Breathing muy lento + sway sutil + drift mínimo. Movimiento casi imperceptible como un jardín zen. Ideal para paisajes serenos.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 3 + depth * 10,
      mouseVelocityInfluence: 0.15,
      inertia: 0.25,
      breathing: true,
      breathingAmp: 0.35 + depth * 0.25,
      sway: true,
      swayAmp: 0.2,
      driftX: depth > 0.5,
      driftAmp: 0.2,
      floatY: depth > 0.7,
      floatAmp: 0.25,
      phaseOffset: primePhase(i),
      durationMultiplier: 2.2,
    }),
    base: {
      intensity: 0.6,
      speed: 0.55,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: true,
      shimmerEnabled: false,
      chromaticAberration: 0.3,
      vignette: 0.2,
      renderMode: "css",
      mouseSmoothing: 0.03,
    },
    effects: { dust: true },
  },
  {
    id: "lava",
    name: "Lava",
    emoji: "🌋",
    category: "dramatic",
    tagline: "Magma fluyente con calor",
    description:
      "Liquid intenso + hue drift cálido + glow naranja + wave. Simula el movimiento convectivo de la lava incandescente.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 5 + depth * 14,
      mouseVelocityInfluence: 0.3,
      inertia: 0.35,
      breathing: true,
      breathingAmp: 0.5,
      sway: true,
      swayAmp: 0.4,
      liquid: true,
      liquidScale: 12 + depth * 10,
      wave: true,
      waveAmp: 0.9,
      glow: true,
      glowAmp: 0.6 + depth * 0.4,
      hueDrift: true,
      hueDriftAmp: 5,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1.25,
      speed: 0.65,
      parallaxEnabled: true,
      liquidEnabled: true,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 1.8,
      vignette: 0.4,
      renderMode: "css",
      mouseSmoothing: 0.05,
    },
    effects: { embers: true, lightleak: true },
  },
  {
    id: "prism",
    name: "Prism",
    emoji: "🔮",
    category: "abstract",
    tagline: "Prisma refractante arcoíris",
    description:
      "Hue drift extremo + chromatic aberration + ripple + glow. La imagen se descompone como a través de un prisma que crea arcoíris.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 7 + depth * 20,
      mouseVelocityInfluence: 0.45,
      inertia: 0.25,
      breathing: true,
      breathingAmp: 0.4,
      ripple: true,
      rippleAmp: 3 + depth * 3,
      hueDrift: true,
      hueDriftAmp: 18 + depth * 10,
      chromatic: true,
      chromaticAmp: 3,
      glow: depth > 0.5,
      glowAmp: 0.5,
      sway3d: true,
      sway3dAmp: 2,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1.2,
      speed: 0.9,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 4.2,
      vignette: 0.3,
      renderMode: "css",
      mouseSmoothing: 0.05,
    },
    effects: { bokeh: true, dust: true, lightleak: true },
  },
  {
    id: "ghost",
    name: "Ghost",
    emoji: "👻",
    category: "dramatic",
    tagline: "Espectral etéreo y frío",
    description:
      "Hue drift frío + focus pull + drift lento + opacidad pulsante. Crea appariciones espectrales que aparecen y desaparecen.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 4 + depth * 16,
      mouseVelocityInfluence: 0.2,
      inertia: 0.4,
      breathing: true,
      breathingAmp: 0.6,
      sway: true,
      swayAmp: 0.35,
      floatY: true,
      floatAmp: 0.6 + depth * 0.4,
      driftX: true,
      driftAmp: 0.5,
      focusPull: true,
      focusAmp: 1.5,
      hueDrift: true,
      hueDriftAmp: 8,
      glow: true,
      glowAmp: 0.4,
      phaseOffset: primePhase(i),
      durationMultiplier: 1.5,
    }),
    base: {
      intensity: 0.85,
      speed: 0.6,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 1.2,
      vignette: 0.35,
      renderMode: "css",
      mouseSmoothing: 0.04,
    },
    effects: { fog: true, dust: true, lightleak: true },
  },
  {
    id: "origami",
    name: "Origami",
    emoji: "🦢",
    category: "abstract",
    tagline: "Papel plegado 3D",
    description:
      "Z-tilt + sway3d + twist + breathing. Las capas se pliegan como papel origami, rotando en 3D con elegancia.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 5 + depth * 18,
      mouseVelocityInfluence: 0.35,
      inertia: 0.2,
      breathing: true,
      breathingAmp: 0.45,
      zTilt: true,
      zTiltAmp: 3 + depth * 3,
      sway3d: true,
      sway3dAmp: 4 + depth * 3,
      twist: depth > 0.5,
      twistAmp: 0.5,
      shadowDrift: true,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1,
      speed: 0.85,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: false,
      shimmerEnabled: true,
      chromaticAberration: 0.6,
      vignette: 0.3,
      renderMode: "css3d",
      mouseSmoothing: 0.05,
      perspective: 1400,
      rotate3dStrength: 10,
    },
    effects: { dust: true },
  },
  {
    id: "neon",
    name: "Neon",
    emoji: "💡",
    category: "cyberpunk",
    tagline: "Neón brillante cyberpunk",
    description:
      "Glow extremo + chromatic + hue drift + scan. Estética neon cyberpunk con brillos eléctricos y aberración cromática.",
    v2: true,
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      parallaxStrength: 6 + depth * 22,
      mouseVelocityInfluence: 0.55,
      inertia: 0.2,
      breathing: true,
      breathingAmp: 0.5 + depth * 0.3,
      glow: true,
      glowAmp: 1 + depth * 0.6,
      chromatic: true,
      chromaticAmp: 2.5 + depth * 1.5,
      hueDrift: true,
      hueDriftAmp: 10,
      scan: depth > 0.4,
      scanAmp: 0.5,
      jitter: depth > 0.6,
      jitterAmp: 0.3,
      phaseOffset: primePhase(i),
    }),
    base: {
      intensity: 1.35,
      speed: 1.1,
      parallaxEnabled: true,
      liquidEnabled: false,
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 4.5,
      vignette: 0.45,
      renderMode: "css",
      mouseSmoothing: 0.04,
    },
    effects: { grain: true, lightleak: true },
  },

  // ============ AWWWARDS PRESET ============
  // El preset definitivo: nubes pasan, viento sopla, todo respira en loop orgánico
  {
    id: "vivo",
    name: "Vivo",
    emoji: "🌿",
    tagline: "Vida orgánica en loop — nubes, viento, respiración",
    description:
      "El preset definitivo. Las capas lejanas (cielo/nubes) derivan horizontalmente como viento real. " +
      "Las capas medias respiran y se balancean como vegetación. El sujeto flota suavemente. " +
      "Todo usa duraciones primas para que NUNCA se sincronice. El efecto es sutil pero hipnótico — " +
      "la imagen se siente viva, respirando, como un jardín con brisa.",
    category: "calm",
    buildLayer: (depth, i) => ({
      ...DEFAULT_LAYER_ANIM,
      // Parallax suave — suficiente para sentir profundidad sin desarmar
      parallaxStrength: 4 + depth * 14,
      mouseVelocityInfluence: 0.25,
      inertia: 0.2,

      // === CAPAS LEJANAS (depth < 0.3) — CIELO Y NUBES ===
      // Derivan horizontalmente como viento real, lentamente
      driftX: depth < 0.3,
      driftAmp: 0.8 + (0.3 - depth) * 2, // más lejos = más deriva
      // Flotan muy sutilmente
      floatY: depth < 0.3,
      floatAmp: 0.3,

      // === CAPAS MEDIAS (0.3 < depth < 0.7) — VEGETACIÓN, MONTAÑAS ===
      // Respiran como seres vivos
      breathing: depth >= 0.3,
      breathingAmp: 0.4 + depth * 0.3,
      // Se balancean como con brisa
      sway: depth >= 0.3,
      swayAmp: 0.3 + depth * 0.2,
      // Onda sutil — como hojas moviéndose
      wave: depth >= 0.4 && depth < 0.8,
      waveAmp: 0.3,

      // === CAPAS CERCANAS (depth > 0.7) — SUJETO, PRIMER PLANO ===
      // Flotan suavemente como suspendidos en el aire
      floatY: depth >= 0.7,
      floatAmp: 0.5,
      // Respiración más profunda
      breathingAmp: depth >= 0.7 ? 0.6 : 0.4 + depth * 0.3,

      // Glow sutil en todas las capas — luz que pulsa
      glow: true,
      glowAmp: 0.2 + depth * 0.15,

      // Phase offset prime para desincronizar
      phaseOffset: primePhase(i),
      // Velocidad orgánica — no demasiado rápida
      durationMultiplier: 0.85 + depth * 0.3,
    }),
    base: {
      intensity: 0.85,  // sutil pero perceptible
      speed: 0.8,       // lento y orgánico
      parallaxEnabled: true,
      liquidEnabled: false,  // sin distorsión líquida — limpio
      particlesEnabled: true,
      shimmerEnabled: true,
      chromaticAberration: 0.4,  // mínimo
      vignette: 0.2,   // sutil
      renderMode: "css",
      mouseSmoothing: 0.04,  // suave
    },
    // Atmósfera: polvo sutil flotando + light leak cálido
    effects: { dust: true, lightleak: true },
  },
];

export const PRESET_MAP: Record<PresetId, PresetMeta> = PRESETS.reduce(
  (acc, p) => {
    acc[p.id] = p;
    return acc;
  },
  {} as Record<PresetId, PresetMeta>
);

export function buildAnimationFromPreset(
  presetId: PresetId,
  layerIds: string[],
  layerDepths: Record<string, number>
): AnimationConfig {
  const preset = PRESET_MAP[presetId];
  const layers: Record<string, LayerAnimationConfig> = {};
  layerIds.forEach((id, i) => {
    const depth = layerDepths[id] ?? 0.5;
    layers[id] = { layerId: id, ...preset.buildLayer(depth, i, layerIds.length) };
  });

  const effects = ALL_EFFECTS.reduce(
    (acc, e) => {
      acc[e] = preset.effects?.[e] ?? false;
      return acc;
    },
    {} as Record<EffectType, boolean>
  );

  return {
    preset: presetId,
    intensity: preset.base.intensity,
    speed: preset.base.speed,
    parallaxEnabled: preset.base.parallaxEnabled,
    liquidEnabled: preset.base.liquidEnabled,
    particlesEnabled: preset.base.particlesEnabled,
    shimmerEnabled: preset.base.shimmerEnabled,
    chromaticAberration: preset.base.chromaticAberration,
    vignette: preset.base.vignette,
    reducedMotion: false,
    renderMode: preset.base.renderMode,
    mouseSmoothing: preset.base.mouseSmoothing,
    perspective: preset.base.perspective ?? 1000,
    rotate3dStrength: preset.base.rotate3dStrength ?? 8,
    scrollParallax: 0.4,
    entranceEnabled: true,
    colorGrade: "none",
    letterbox: false,
    // v3: presets can now enable gateWeave (vintage preset)
    gateWeave: (preset.base as any).gateWeave ?? false,
    dofEnabled: false,
    focusDepth: 0.5,
    aperture: 0.3,
    focusMode: "manual",
    scaleWithDepth: true,
    sceneComposition: "free",
    atmoLightCycle: false,
    atmoFogDrift: false,
    atmoTimelapse: false,
    atmoSeasonal: false,
    depthFogEnabled: false,
    depthFogDensity: 0.4,
    bloomEnabled: false,
    bloomIntensity: 0.5,
    toneMapStrength: 0.6,
    relightingEnabled: false,
    relightingAzimuth: 45,
    relightingElevation: 45,
    relightingIntensity: 0.5,
    relightingColorTemp: 0.3,
    colorScriptEnabled: false,
    colorScriptAct: -1,
    motionBlurEnabled: false,
    motionBlurStrength: 0.5,
    // v3: mathematical motion engine (exact, non-deforming, harmonic)
    useMathEngine: false,
    layers,
    effects,
  };
}
