// Shared types for the Alive Image studio (v2 — professional layer editor)

export type LayerRole =
  | "background"
  | "midground"
  | "subject"
  | "foreground"
  | "depth"
  | "effect" // procedural overlay (fog, snow, rays, etc.)
  | "custom"; // user-extracted element

export type LayerSource =
  | "ai" // generated by VLM/image-edit
  | "depth-slice" // sliced from depth map via K-means
  | "custom" // user-named extraction
  | "effect"; // procedural overlay

export type DecompositionStrategy =
  | "depth-slice" // mathematical K-means slicing (fast, deterministic)
  | "ai-extract"; // per-element AI extraction (thorough, slower)

export type PipelineStep =
  | "upload"
  | "analyze"
  | "decompose"
  | "animate";

export type EffectType =
  | "fog"
  | "snow"
  | "rain"
  | "godrays"
  | "bokeh"
  | "dust"
  | "lightleak"
  | "grain"
  // canvas-based particle effects (Nivel 4)
  | "smoke"
  | "fire"
  | "embers";

export type BlendMode =
  | "normal"
  | "multiply"
  | "screen"
  | "overlay"
  | "soft-light"
  | "hard-light"
  | "color-dodge"
  | "lighten"
  | "darken"
  | "difference";

/** Editable per-layer transform (manipulated in the visual editor) */
export interface LayerTransform {
  x: number; // px offset
  y: number; // px offset
  scale: number; // 1 = original
  rotation: number; // deg
  opacity: number; // 0..1
  blur: number; // px
  blendMode: BlendMode;
  visible: boolean;
  locked: boolean;
  zOverride?: number; // explicit z-order (undefined = by depth)
}

export interface ImageLayer {
  id: string;
  name: string;
  role: LayerRole;
  /** 0 = farthest, 1 = closest. Drives parallax + z-order. */
  depth: number;
  /** public URL of the layer image (empty for effect layers) */
  url: string;
  /** short semantic description from VLM */
  description: string;
  source: LayerSource;
  effectType?: EffectType;
  transform: LayerTransform;
}

export interface SceneAnalysis {
  sceneDescription: string;
  subject: string;
  mood: string;
  palette: string[];
  /** ordered back → front, can be 6-10 layers */
  layers: Array<{
    name: string;
    role: LayerRole;
    depth: number;
    description: string;
    /** optional extraction prompt for image-edit to isolate this element */
    extractPrompt?: string;
  }>;
  recommendedPreset: string;
}

export type PresetId =
  | "dream"
  | "float"
  | "pulse"
  | "liquid"
  | "cinematic3d"
  | "shimmer"
  | "boil"
  | "kenburns"
  // new v2 presets
  | "aurora"
  | "underwater"
  | "ethereal"
  | "noir"
  | "cosmic";

export interface SpringPhysics {
  stiffness: number; // 1..200
  damping: number; // 1..100
  mass: number; // 0.1..5
}

export interface LayerAnimationConfig {
  layerId: string;

  // === parallax ===
  parallaxStrength: number; // px at max mouse
  mouseVelocityInfluence: number; // 0..2 — react to mouse speed
  inertia: number; // 0..1 — keep moving after mouse stops

  // === organic effects (each can be toggled + has amplitude) ===
  breathing: boolean;
  breathingAmp: number;
  sway: boolean;
  swayAmp: number;
  floatY: boolean;
  floatAmp: number;
  driftX: boolean;
  driftAmp: number;

  // NEW v2 effects
  twist: boolean; // oscillating rotation, larger amplitude than sway
  twistAmp: number;
  jitter: boolean; // sub-pixel tremor (boil)
  jitterAmp: number;
  wave: boolean; // horizontal sinusoidal displacement
  waveAmp: number;
  glow: boolean; // brightness/drop-shadow pulse
  glowAmp: number;
  hueDrift: boolean; // slow hue-rotate
  hueDriftAmp: number; // deg total rotation (e.g. 8)
  focusPull: boolean; // oscillating blur (DoF)
  focusAmp: number; // px max blur
  shadowDrift: boolean; // drop-shadow moves opposite
  chromatic: boolean; // per-layer RGB split
  chromaticAmp: number;

  // === liquid (SVG) ===
  liquid: boolean;
  liquidScale: number;

  // === physics ===
  spring: SpringPhysics;
  phaseOffset: number; // 0..1 — staggered animation start
  durationMultiplier: number; // 0.25..3 per-layer speed

  // === visual ===
  blur: number;
  opacity: number;
}

export interface AnimationConfig {
  preset: PresetId;
  intensity: number;
  speed: number;
  parallaxEnabled: boolean;
  liquidEnabled: boolean;
  particlesEnabled: boolean;
  shimmerEnabled: boolean;
  chromaticAberration: number;
  vignette: number;
  reducedMotion: boolean;
  /** render mode: 'css' = Framer+SVG, 'css3d' = true 3D perspective, 'webgl' = depth shader, 'kenburns3d' = point cloud */
  renderMode: "css" | "css3d" | "webgl" | "kenburns3d";
  /** global mouse smoothing */
  mouseSmoothing: number; // 0.01..0.3
  /** 3D perspective strength (for css3d mode) in px */
  perspective: number; // 600..2000
  /** 3D rotation amount (for css3d mode) in deg */
  rotate3dStrength: number; // 2..20
  layers: Record<string, LayerAnimationConfig>;
  /** effect-layer config (which procedural overlays are active) */
  effects: Record<EffectType, boolean>;

  // === Hero mode ===
  /** scroll-bound parallax strength (0..1, how much layers move per scroll) */
  scrollParallax: number;
  /** entrance reveal: staggered layer fade/scale on load */
  entranceEnabled: boolean;
  /** color grading preset */
  colorGrade: ColorGrade;
  /** letterbox bars (cinematic 2.39:1) */
  letterbox: boolean;
  /** gate weave (sub-pixel film jitter) */
  gateWeave: boolean;

  // === 2.5D pipeline (Disguise-style) ===
  /** DOF: organic focus pull based on layer depth (not baked blur) */
  dofEnabled: boolean;
  /** focus depth 0..1 (where the focal plane is in Z) */
  focusDepth: number;
  /** aperture 0..1 (higher = more bokeh/falloff) */
  aperture: number;
  /** focus mode: 'manual' = slider, 'object' = track a layer */
  focusMode: "manual" | "object";
  /** layer ID to track when focusMode = 'object' */
  focusLayerId?: string;
  /** scale-with-depth: layers auto-scale based on Z position */
  scaleWithDepth: boolean;

  // === Scene composition ===
  /** scene composition preset (which layers are anchors vs drifters) */
  sceneComposition: import("./scene-compositions").SceneCompositionId;

  // === Atmospheric animations ===
  /** light cycle (day/night) */
  atmoLightCycle: boolean;
  /** fog drift */
  atmoFogDrift: boolean;
  /** timelapse sun arc */
  atmoTimelapse: boolean;
  /** seasonal hue rotation */
  atmoSeasonal: boolean;

  // === Phase 2: pro cinematic ===
  /** depth fog volumétrico */
  depthFogEnabled: boolean;
  depthFogDensity: number;
  /** bloom + ACES tone mapping */
  bloomEnabled: boolean;
  bloomIntensity: number;
  toneMapStrength: number;
}

/** .2p5d export format (Disguise-compatible container) */
export interface P2_5DAsset {
  version: string;
  origin: { x: number; y: number; z: number };
  fov: number;
  plates: Array<{
    name: string;
    colorUrl: string;
    depthUrl?: string;
    depth: number;
    z: number;
    scale: number;
    visible: boolean;
    locked: boolean;
  }>;
  camera: {
    fov: number;
    focusMode: "manual" | "object";
    focusDepth: number;
    aperture: number;
  };
}

export type ColorGrade =
  | "none"
  | "teal-orange"
  | "bleach-bypass"
  | "portra"
  | "blade-runner"
  | "noir-film";

export interface TextOverlay {
  headline: string;
  subheadline: string;
  cta: string;
  align: "left" | "center";
  position: "top" | "center" | "bottom";
  enabled: boolean;
}

export interface ProjectState {
  id: string;
  originalUrl: string;
  originalDataUrl?: string;
  width: number;
  height: number;
  analysis?: SceneAnalysis;
  layers: ImageLayer[];
  depthMapUrl?: string;
  backgroundUrl?: string;
  animation: AnimationConfig;
  status:
    | "idle"
    | "uploaded"
    | "analyzing"
    | "analyzed"
    | "separating"
    | "ready"
    | "error";
  error?: string;
  /** id of currently selected layer (for editor) */
  selectedLayerId?: string;
  /** which decomposition strategy the user picked */
  strategy?: DecompositionStrategy;
  /** current pipeline step (for the progress indicator) */
  pipelineStep?: PipelineStep;
  /** text overlay config (hero mode) */
  textOverlay?: TextOverlay;
  /** hero mode active (full-viewport scroll-driven) */
  heroMode?: boolean;
}

export const DEFAULT_TRANSFORM: LayerTransform = {
  x: 0,
  y: 0,
  scale: 1,
  rotation: 0,
  opacity: 1,
  blur: 0,
  blendMode: "normal",
  visible: true,
  locked: false,
};

export const DEFAULT_SPRING: SpringPhysics = {
  stiffness: 50,
  damping: 20,
  mass: 0.5,
};

export const DEFAULT_LAYER_ANIM: Omit<LayerAnimationConfig, "layerId"> = {
  parallaxStrength: 20,
  mouseVelocityInfluence: 0.3,
  inertia: 0.15,
  breathing: true,
  breathingAmp: 1,
  sway: true,
  swayAmp: 1,
  floatY: false,
  floatAmp: 1,
  driftX: false,
  driftAmp: 1,
  twist: false,
  twistAmp: 0.6,
  jitter: false,
  jitterAmp: 1,
  wave: false,
  waveAmp: 1,
  glow: false,
  glowAmp: 1,
  hueDrift: false,
  hueDriftAmp: 8,
  focusPull: false,
  focusAmp: 2,
  shadowDrift: false,
  chromatic: false,
  chromaticAmp: 1.5,
  liquid: false,
  liquidScale: 8,
  spring: DEFAULT_SPRING,
  phaseOffset: 0,
  durationMultiplier: 1,
  blur: 0,
  opacity: 1,
};

export const ALL_EFFECTS: EffectType[] = [
  "fog",
  "snow",
  "rain",
  "godrays",
  "bokeh",
  "dust",
  "lightleak",
  "grain",
  "smoke",
  "fire",
  "embers",
];
